### ISSUE TITLE
Interface : Patch view > create node from right click (context menu)

### ISSUE THREAD

**Issue by benkuper** [elliotwoods/ofxRulr#127]
Suggestion : 
Instead of having an almost full screen window for node creation, use a simple a hierarchy-based right click context menu.

**Comment by elliotwoods** [comment]
currently i disagree with this
i don't think it's necessary to make the node-browser more minimal

i think switching to a different context makes sense in quite a few situations
(e.g. i've been considering export dialogues which also come up full-screen in the same way)
in this particular situation i think a context switch is more comfortable

also i'm envisaging adding more content to the node browser (e.g. animations on the right showing example of that node's use and/or a text description of what it does and how to use it)

**Comment by benkuper** [comment]
More content on this interface could be interesting, yes.
The freeze makes it hard currently, but if this issue is fixed, i agree that that kind of interface can me more suited if there is more content shown.

**Comment by elliotwoods** [comment]
agree the slow load needs to be fixed
closing this one for now
