### ISSUE TITLE
Bug (Interface) : Double click on Patch view freezes for few seconds before opening node creation panel

### ISSUE THREAD

**Issue by benkuper** [elliotwoods/ofxRulr#128]
When double-clicking on Patch view to create a node, the app freezes for a certain amount of time before opening the node creation panel. This freeze time seems to increase with the usage time of the app (or each time the node creation panel is opened) and can go up to 5 or 6 seconds.
As the app keeps the mouse events that occured during this freeze time and throws them when it unfreezes, if the user clicks while the app is frozen, it will have unwanted behavior.
(See issue #127 for full alternative solution)

**Comment by elliotwoods** [comment]
yeah i get this
no idea where it's coming from, but i should go and track it down

**Comment by elliotwoods** [comment]
it's possibly related to the fact that it has to create one instance of every class to poll it for static content (e.g. icons) as you can't have static virtual methods in c++ (e.g. to ask a class its type name or icon).
these should be cached, but obviously something isn't using the cache still. will investigate

**Comment by elliotwoods** [comment]
seems to have been fixed by improvment to ofxCvGui:
https://github.com/elliotwoods/ofxCvGui/commit/90e12142c18dd5f23b301468413f829b5e1b7f03
