### ISSUE TITLE
Interface : Change " . . . " separator image in inspector

### ISSUE THREAD

**Issue by benkuper** [elliotwoods/ofxRulr#131]
This image is often the convention for "More if you click me" interaction.
Suggestion :
Draw a simple line, and don't show the vertical line at the right that also suggests it is an interactable element.

**Comment by elliotwoods** [comment]
good idea

there's also the possibility of more strongly defining hierarchies of widget elements (e.g. collapsable, or more graphical indication of which widgets belong to which header)
right now the hierarchy isn't strict and the developer is free to do as s/he likes.

but anyway, for the time being the issue you highlight should be a simple fix.

**Comment by elliotwoods** [comment]
https://github.com/elliotwoods/ofxCvGui/commit/ae210fc7fb250838f44bb44c3e189424c95a64b5
