### ISSUE TITLE
Feature : Implement KinectV2 RGB feed as ofxMachineVision::Device::Updating

### ISSUE THREAD

**Issue by benkuper** [elliotwoods/ofxRulr#134]
In a setup with only a video projector and a kinect V2, we should be able to use the mesh From 2D graycode with the Kinect RGB camera.

**Comment by elliotwoods** [comment]
changed the title to describe the task properly
should be easy
~20 lines of code to implement a camera class for ofxMachineVision (would add this class to the Kinect plugin)
