### ISSUE TITLE
Feature : A better 3D grid

### ISSUE THREAD

**Issue by elliotwoods** [elliotwoods/ofxRulr#44]
Issues right now:
- No mip mapping
- Needs 6 sides of cube (and turn culling back on)
- Drawing is very slow (for loop on drawing images. Much better if done with wrapped texture coordinates on 6 planes with texture transforms, or using shader techniques)

Possible features:
- Shadows on floor plane (would be amazing, everything would be much easier to find, should use drawStencil function)

**Comment by elliotwoods** [comment]
(everything disucssed here is in the Core project, not the Nodes project)

the class `ofxRulr::Graph::World` contains all the nodes
`ofxRulr::Graph::Editor::Patch` is a node, so is `ofxRulr::Graph::Summary`

These 2 nodes are the top and bottom view when you start Rulr (Summary is the 3D view).
All the user's nodes are inside the `Patch` node.

So we want to edit this file:
https://github.com/elliotwoods/ofxRulr/blob/master/Core/src/ofxRulr/Graph/Summary.cpp

specifically the `drawGrid` function

**Comment by prisonerjohn** [comment]
I'm having issues because of `ofxAssets`. Textures need to be `GL_TEXTURE_2D` for mip mapping and wrapped textures to work properly, but it looks like they're defaulting to `GL_TEXTURE_ARB_RECTANGLE`. 

This doesn't work:
```cpp
auto wasArbTex = ofGetUsingArbTex();
ofDisableArbTex();
this->grid = &ofxAssets::image("ofxRulr::grid-10");
this->grid->getTexture().enableMipmap();
this->grid->getTexture().generateMipmap();
this->grid->getTexture().setTextureWrap(GL_REPEAT, GL_REPEAT);
if (wasArbTex) ofEnableArbTex();
```

This does:
```cpp
ofDisableArbTex();
this->grid2d = new ofImage();
this->grid2d->load("assets/ofxRulr/images/grid-10.png");
this->grid2d->getTexture().enableMipmap();
this->grid2d->getTexture().generateMipmap();
this->grid2d->getTexture().setTextureWrap(GL_REPEAT, GL_REPEAT);
if (wasArbTex) ofEnableArbTex();
```

Does `ofxAssets` preload images? If so, is there a way to override that in this case?

Alternatively, I usually like working with `GL_TEXTURE_2D` as the default as it's simpler to deal with... But it might break a bunch of pre-existing texture mapping code.

**Comment by elliotwoods** [comment]
how about

```cpp
ofDisableArbTex();
this->grid.load(ofxAssets::image("ofxRulr::grid-10"));
this->grid.enableMipmap();
this->grid.generateMipmap();
this->grid.setTextureWrap(GL_REPEAT, GL_REPEAT);
if (wasArbTex) ofEnableArbTex();
```

(presuming `this->grid` is an `ofTexture`)

seems sensible to me
